const express = require("express");
const bcrypt = require("bcryptjs");
const jwt = require("jsonwebtoken");
const rateLimit = require("express-rate-limit");
const mongoose = require("mongoose");
const User = require("../models/User"); const Account = require("../models/Account"); const Instrument = require("../models/Instrument"); const Watchlist = require("../models/Watchlist"); const Order = require("../models/Order"); const Transaction = require("../models/Transaction"); const PriceSnapshot = require("../models/PriceSnapshot");
const { authenticate } = require("../middleware/auth"); const { ApiError, asyncHandler, send } = require("../utils/api"); const { publicInstrument } = require("../services/instrumentService"); const { executeTrade } = require("../services/tradeService"); const { getPortfolio } = require("../services/portfolioService"); const { status, refreshMarketData, getChartHistory, historyCapabilities } = require("../services/marketDataService");
const router = express.Router();
const authLimit = rateLimit({ windowMs: 15 * 60 * 1000, limit: 20, standardHeaders: true, legacyHeaders: false, message: { success: false, error: { code: "RATE_LIMITED", message: "Too many authentication attempts" } } });
const createToken = (user) => jwt.sign({ sub: user.id, email: user.email }, process.env.JWT_SECRET, { expiresIn: process.env.JWT_EXPIRES_IN || "30m" });
const validPassword = (value) => typeof value === "string" && value.length >= 8 && value.length <= 128;

router.post("/auth/signup", authLimit, asyncHandler(async (req, res) => {
  const { name, email, password } = req.body;
  if (typeof name !== "string" || name.trim().length < 2 || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email || "") || !validPassword(password)) throw new ApiError(422, "Provide a name, valid email, and password of at least 8 characters", "VALIDATION_ERROR");
  const normalizedEmail = email.trim().toLowerCase(); if (await User.exists({ email: normalizedEmail })) throw new ApiError(409, "An account already exists for this email", "EMAIL_TAKEN");
  const session = await mongoose.startSession(); let user; try { await session.withTransaction(async () => { [user] = await User.create([{ name: name.trim(), email: normalizedEmail, passwordHash: await bcrypt.hash(password, 12) }], { session }); await Account.create([{ user: user._id, openingCashPaise: 10000000, availableCashPaise: 10000000 }], { session }); }); } finally { await session.endSession(); }
  send(res, 201, { user: user.toPublic(), accessToken: createToken(user), expiresIn: process.env.JWT_EXPIRES_IN || "30m" }, "Account created");
}));
router.post("/auth/login", authLimit, asyncHandler(async (req, res) => { const { email, password } = req.body; if (typeof email !== "string" || typeof password !== "string") throw new ApiError(422, "Email and password are required", "VALIDATION_ERROR"); const user = await User.findOne({ email: email.trim().toLowerCase() }).select("+passwordHash"); if (!user || !(await bcrypt.compare(password, user.passwordHash))) throw new ApiError(401, "Invalid email or password", "INVALID_CREDENTIALS"); send(res, 200, { user: user.toPublic(), accessToken: createToken(user), expiresIn: process.env.JWT_EXPIRES_IN || "30m" }); }));

router.get("/market-data/status", asyncHandler(async (req, res) => send(res, 200, { marketData: await status() })));
router.get("/market-data/history-capabilities/:symbol", asyncHandler(async (req, res) => { const instrument = await Instrument.findOne({ symbol: req.params.symbol.toUpperCase() }); if (!instrument) throw new ApiError(404, "Instrument not found", "INSTRUMENT_NOT_FOUND"); send(res, 200, { marketData: await historyCapabilities(instrument) }); }));
router.use(authenticate);
router.post("/market-data/refresh", asyncHandler(async (req, res) => send(res, 200, { marketData: await refreshMarketData() })));
router.get("/users/me", asyncHandler(async (req, res) => { const user = await User.findById(req.auth.sub); if (!user) throw new ApiError(401, "User no longer exists", "INVALID_TOKEN"); send(res, 200, { user: user.toPublic() }); }));
router.patch("/users/me", asyncHandler(async (req, res) => { const { name } = req.body; if (typeof name !== "string" || name.trim().length < 2 || name.trim().length > 80) throw new ApiError(422, "Name must be between 2 and 80 characters", "VALIDATION_ERROR"); const user = await User.findByIdAndUpdate(req.auth.sub, { name: name.trim() }, { new: true }); send(res, 200, { user: user.toPublic() }); }));
router.get("/instruments", asyncHandler(async (req, res) => { const instruments = await Instrument.find().sort({ symbol: 1 }); send(res, 200, { instruments: instruments.map(publicInstrument) }); }));
router.get("/instruments/:symbol", asyncHandler(async (req, res) => { const instrument = await Instrument.findOne({ symbol: req.params.symbol.toUpperCase() }); if (!instrument) throw new ApiError(404, "Instrument not found", "INSTRUMENT_NOT_FOUND"); send(res, 200, { instrument: publicInstrument(instrument) }); }));
router.get("/instruments/:symbol/history", asyncHandler(async (req, res) => { const instrument = await Instrument.findOne({ symbol: req.params.symbol.toUpperCase() }); if (!instrument) throw new ApiError(404, "Instrument not found", "INSTRUMENT_NOT_FOUND"); const range = String(req.query.range || "1M").toUpperCase(); const chart = await getChartHistory(instrument, range); const history = chart.points.slice().sort((a, b) => new Date(a.createdAt) - new Date(b.createdAt)).map((item) => ({ pricePaise: item.pricePaise, at: item.createdAt })); send(res, 200, { history, current: publicInstrument(instrument), range, historySource: chart.source, historyMessage: chart.message || null }); }));
router.get("/watchlist", asyncHandler(async (req, res) => { const items = await Watchlist.find({ user: req.auth.sub }).populate("instrument").sort({ createdAt: -1 }); send(res, 200, { watchlist: items.map((item) => ({ id: item.id, instrument: publicInstrument(item.instrument) })) }); }));
router.post("/watchlist", asyncHandler(async (req, res) => { const symbol = String(req.body.symbol || "").toUpperCase(); const instrument = await Instrument.findOne({ symbol }); if (!instrument) throw new ApiError(404, "Instrument not found", "INSTRUMENT_NOT_FOUND"); try { const item = await Watchlist.create({ user: req.auth.sub, instrument: instrument._id }); send(res, 201, { watchlistItem: { id: item.id, instrument: publicInstrument(instrument) } }); } catch (error) { if (error.code === 11000) throw new ApiError(409, "Instrument is already on your watchlist", "WATCHLIST_DUPLICATE"); throw error; } }));
router.delete("/watchlist/:symbol", asyncHandler(async (req, res) => { const instrument = await Instrument.findOne({ symbol: req.params.symbol.toUpperCase() }); if (!instrument) throw new ApiError(404, "Instrument not found", "INSTRUMENT_NOT_FOUND"); const result = await Watchlist.deleteOne({ user: req.auth.sub, instrument: instrument._id }); if (!result.deletedCount) throw new ApiError(404, "Watchlist entry not found", "WATCHLIST_NOT_FOUND"); send(res, 204, null); }));
router.get("/account", asyncHandler(async (req, res) => { const account = await Account.findOne({ user: req.auth.sub }); send(res, 200, { account: { openingCashPaise: account.openingCashPaise, availableCashPaise: account.availableCashPaise } }); }));
router.get("/portfolio", asyncHandler(async (req, res) => send(res, 200, { portfolio: await getPortfolio(req.auth.sub) })));
router.get("/holdings", asyncHandler(async (req, res) => { const portfolio = await getPortfolio(req.auth.sub); send(res, 200, { holdings: portfolio.holdings, totals: portfolio.totals }); }));
router.post("/orders", asyncHandler(async (req, res) => { const symbol = String(req.body.symbol || "").toUpperCase(); const side = String(req.body.side || "").toUpperCase(); const quantity = req.body.quantity; if (!/^[A-Z0-9&-]+$/.test(symbol) || !["BUY", "SELL"].includes(side) || !Number.isSafeInteger(quantity) || quantity <= 0) throw new ApiError(422, "symbol, side (BUY or SELL), and positive whole-share quantity are required", "VALIDATION_ERROR"); const trade = await executeTrade({ userId: req.auth.sub, symbol, side, quantity }); send(res, 201, { order: trade }, "Order executed"); }));
router.get("/orders", asyncHandler(async (req, res) => { const orders = await Order.find({ user: req.auth.sub }).populate("instrument", "symbol companyName").sort({ createdAt: -1 }).limit(100); send(res, 200, { orders: orders.map((order) => ({ id: order.id, side: order.side, quantity: order.quantity, status: order.status, executionPricePaise: order.executionPricePaise, executedAt: order.executedAt, instrument: order.instrument })) }); }));
router.get("/transactions", asyncHandler(async (req, res) => { const transactions = await Transaction.find({ user: req.auth.sub }).populate("instrument", "symbol companyName").sort({ createdAt: -1 }).limit(100); send(res, 200, { transactions }); }));
module.exports = router;
